services:
  db:
    build:
      context: ./MYSQL
      dockerfile: ./Dockerfile
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: mysqldb
      MYSQL_ROOT_PASSWORD: master
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    networks:
      - mysqlcomposenetwork
    ports:
      - 3306:3306

  flask:
    build: .
    command: python3 -m flask run --host=0.0.0.0 --port=8000 --debug
    ports:
      - 8000:8000
    volumes:
      - .:/app
    networks:
      - mysqlcomposenetwork
    depends_on:
      - db
  tests:
    build: .
    command: sh -c "pytest tests || tail -f /dev/null"
    volumes:
      - .:/app
    networks:
      - mysqlcomposenetwork
    depends_on:
      - flask

networks:
  mysqlcomposenetwork:
    driver: bridge
